### PR TITLE
Texture update for vines to CC0

### PR DESCRIPTION
**Pull request by sirrobzeroone**
I'll leave this pull request here, understand if these don't end up being used - no stress :)

relates to: https://github.com/mt-mods/plantlife_modpack/issues/20

Happy to take feedback.

recreated the vines and rope textures and releasing them under CC0

### CODE REVIEW

**Review by S-S-X — APPROVED** [review]
Just going through texture files I do like new textures, seems better that old.
That said I've not tested in game and screenshots do not reveal all of it or what wall of vines would look like for example.

However (without testing at all) I guess it can't really be worse. File sizes increase a little bit but I do not have problem with that myself, I guess if needed that could be reduced without losing significant details.

LGTM 👍

**Comment by wsor4035** [comment]
personally think there a downgrade, and this is trying to address a non issue. if your really trying to make a big deal out of the license, you could make the case that these are derivative works on a few of them

**Comment by OgelGames** [comment]
IMO some are better, others are worse. Here are screenshots to compare:
 
screenshot_20220528_145548
screenshot_20220528_145618

**Comment by S-S-X** [comment]
Looking at OgelGames's screenshots:
Rope and vines besides rope are a lot better in my opinion, especially rope.
Textures for first 2 vines reading from left are worse mostly because of tiling pattern.
Maybe brightness should be adjusted to make 1st from left and first 2 from right a bit darker.

**Comment by SwissalpS** [comment]
2nd from left was better as it was an overlay to the entire node behind it.
The new rope is a lot better.
I agree about darkening especially the first one.

**Comment by sirrobzeroone** [comment]
Just for FYI - I am watching comments once they settle I'll adjust - agree on the tiling pattern on Vine1 hadn't noticed that myself looks pretty bad. V2 I'll have a play around with so it edge to edge tiles as well both can be darkened very easily. Glad the ropes okay spent way to long trying different pixel patterns before I stumbled on what appeared obvious once I'd done it.....

**Comment by sirrobzeroone** [comment]
Darkened up the vines a little you can see I leftt hem hanging so logn they grow...picys post me doing the quick fix above

Let me know if the colors and patterns on V1/V2 are slightly better did any of the others need darkening? Like this screenshot layout way more so I'll use it to replace the screenshot in vines as well - also lowers file size as less busy.
screenshot

**Pull request merged**
