### PR TITLE
API for dynamic plant spawning

### PR DESCRIPTION
**Pull request by Niklp09**
Next step for https://github.com/mt-mods/plantlife_modpack/issues/27

- Clean up `bushes` mod (removal of global table, code order)
- Add simple api to attach a function to new spawned plants (works except the y pos is sometimes wrong)

The new decoration definitions for bushes are just dummys, this is a job for people who are familiar w/ noise params

### CODE REVIEW

**Comment by wsor4035** [comment]
sorry, i dont think adding an api mod here is the right way to do this. additionally it is recreating biome lib to a degree since biome lib was originally code extracted from this mod 🙃

**Comment by Niklp09** [comment]
I tried to recreate biome_lib in https://github.com/mt-mods/plantlife_modpack/pull/41 (and failed, lol). This mod has only one simple function to de-duplicate code that we need to remove biome_lib. I won't call this biome_lib 2.0.

**Comment by wsor4035** [comment]
did some reading. this could be done much more performantly with schematic decorations and y slice probability to spice it up a bit

**Comment by Niklp09** [comment]
Doesn't seem to be needed.

**Pull request closed without merging**
