### PR TITLE
Breaking up flowers_plus mod

### PR DESCRIPTION
**Pull request by JordanL2**
Splitting up flowers_plus into separate mods for seaweed, sunflowers and waterlilies, for clarity and so the user can disable them individually.

Fixed sunflower maximum heat.

Removed spawning, as we're already creating these things at worldgen.

### CODE REVIEW

**Comment by wsor4035** [comment]
if your going to create new mods, it is probably best to namespace them, esepecially considering how generic that names are. for example pl_seaweed, pl_waterlily, pl_sunflowers

**Comment by wsor4035** [comment]
at least from https://content.minetest.net/metapackages/flowers_plus/ it seems the depreciating the flowers_plus modname is ok

**Comment by JordanL2** [comment]
Good point, will rename them.

**Comment by JordanL2** [comment]
Done, prefixed with "plantlife_" as that seems to be the convention with other modpacks.

**Comment by JordanL2** [comment]
Added settings for each mod to control spawning.

**Comment by JordanL2** [comment]
Since the along_shore mod does nothing, since it was all moved into flowers_plus a long time ago, I've removed it.

Also fixed plantlife_seaweed since it was generating "along_shore:seaweed" items, and then aliasing them to the "flowers:seaweed" items.

**Comment by wsor4035** [comment]
> Done, prefixed with "plantlife_" as that seems to be the convention with other modpacks.

might be a bit nit picky, but i would suggest a two letter abbreviation as it prevent you from having massive modnames. see nodecore, farlands_reloaded, mineclon*, etc.

**Comment by JordanL2** [comment]
The longest is plantlife_waterlilies which is 21, you sure that's too long?

**Comment by JordanL2** [comment]
I think it makes it much clearer what actual modpack it's from.

**Comment by JordanL2** [comment]
Eh ok I'll rename them.

**Comment by JordanL2** [comment]
Done.

**Review by BuckarooBanzay — APPROVED** [review]

**Review by wsor4035 — APPROVED** [review]

**Comment by JordanL2** [comment]
Sorry to bump but does this require anyone else's approval?

**Comment by BuckarooBanzay** [comment]
> Sorry to bump but does this require anyone else's approval?

Don't think so (i don't use that mod anywhere but the changes look good :+1:)

**Pull request merged**
