### PR TITLE
patch ebiomes being bad by loading after it

### PR DESCRIPTION
**Pull request by wsor4035**
should in theory fix https://github.com/mt-mods/plantlife_modpack/issues/60, but didnt actually test it

### CODE REVIEW

**Comment by Niklp09** [comment]
Why do you only add the depend to 3 mods?

**Comment by wsor4035** [comment]
> Why do you only add the depend to 3 mods?

because those are the only ones that could crash, probably should add it to the rest so that the decorations actually exist

**Comment by Niklp09** [comment]
haha yeah, makes sense

**Review by Niklp09 — APPROVED** [review]
+1

**Pull request merged**
