### PR TITLE
use degrotate for sunflowers

### PR DESCRIPTION
**Pull request by Niklp09**
Closes https://github.com/mt-mods/plantlife_modpack/issues/45
Needs mt 5.5 or higher

### CODE REVIEW

**Comment by Niklp09** [comment]
on old clients (5.0.1) the sunflowers all "look" to the south

**Comment by wsor4035** [comment]
tried it, works, does mean if someone specifically had them turned in a direction, might be different.....kinda 🤷 on that, can be fixed with worldedit //param2. regarding requiring minetest 5.5 min otherwise all look south, i dont think thats to big of a deal? does mean that multicraft is affected as there 5.4 based, but maybe they should rebase 😏. the only random thought i have, is maybe eventually could define an on rotate for the screwdriver in mtg in the nodedef, so that players can turn them to specific angles, but then again, maybe turning nature is weird?

**Review by wsor4035 — APPROVED** [review]
see above

**Comment by Niklp09** [comment]
works w/ omnidriver :tm:

**Pull request merged**
